#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx
#  namespace: nginx
#spec:
#  containers:
#    - name: nginx
#      image: summerschool.azurecr.io/summerschool
#       ports:
#      - containerPort: 80  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run:nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: summerschool.azurecr.io/summerschool
        ports:
        - containerPort: 80
