apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  containers:
    - name: nginx
      image: summerschool.azurecr.io/summerschool
      ports:
      - containerPort: 80    
