apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
    - name: nginx
      image: summerschool.azurecr.io/summerschool:latest
      ports:
      - containerPort: 80    