#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-entrypoint
#  namespace: nginx
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 80
#  selector:
#    app: nginx

apiVersion: v1
kind: Service
metadata:
  name: nginx-entrypoint
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx
